name: Docker

env:
  DOTNET_VERSION: 7.0.x

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        default: 'Manual run'
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read

jobs:
  build-and-push:
    timeout-minutes: 15
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: docker build . --tag students-${{ github.event.repository.name }}:develop --file src/Presentation/Dockerfile
