name: Pull request

env:
  DOTNET_VERSION: 7.0.x

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop

concurrency:
  group: ${{ gihub.head_ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  packages: read

jobs:
  test:
    timeout-minutes: 15
    runs-on: self-hosted
    env:
      NUGET_USERNAME: chippr
      NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Test
        run: dotnet test --configuration Release --filter "FullyQualifiedName!~IntergrationTests"
